version: '3'
services:
    golf-stats:
        container_name: golf-stats
        build:
            context: docker-golf-stats
            dockerfile: Dockerfile
        image: golf-stats:latest
        ports:
            - "18888:8080"
        depends_on:
            - redis
        restart: on-failure
    redis:
        container_name: redis
        image: redis:7.2.4-alpine
        command: redis-server --save 60 1 --loglevel error
        volumes:
            - $HOME/golf-stats-data:/data
        restart: unless-stopped
        ports:
            - "16379:6379"